# pulled from Full project: https://gitlab.com/pages/plain-html
image: docker.artifactory.michelin.com/alpine:3.8
pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - dif
